routes/web.php
Route::get('productos', 'Cliente\EstaticoController@PRODUCTOS')->name('productos');

Route::get('calidad', 'Cliente\EstaticoController@calidad')->name('calidad');
Route::get('tecnologia', 'Cliente\EstaticoController@tecnologia')->name('tecnologia');
Route::get('diseno', 'Cliente\EstaticoController@diseno')->name('diseno');
Route::get('quienes-somos', 'Cliente\EstaticoController@quienesSomos')->name('quienes-somos');
Route::get('proveedores', 'Cliente\EstaticoController@proveedores')->name('proveedores');
Route::get('sustentabilidad', 'Cliente\EstaticoController@sustentabilidad')->name('sutentabilidad');


Route::get('aviso-de-privacidad', 'Cliente\EstaticoController@avisoPrivacidad')->name('aviso-de-privacidad');
//Route::view('/aviso-de-privacidad', 'cliente.aviso-de-privacidad');





Route::get('areas-de-practica', 'Cliente\EstaticoController@areasDePractica')->name('areas-de-practica');

Route::view('/ubicacion', 'cliente.ubicacion');


/*Rutas Galerias*/
Route::get('galeria', 'Cliente\GaleriaController@index')->name('galerias.index');
Route::get('galeria/{slug}', 'Cliente\GaleriaController@detalle')->name('galerias.detalle');

/* Rutas promociones */
Route::get('promociones/{slug}', 'Cliente\PromocionController@show')->name('promociones.show');

/* Rutas productos
Route::get('productos', 'Cliente\ProductoController@index')->name('productos.index');
Route::get('productos/{slug}', 'Cliente\ProductoController@show')->name('productos.show');
Route::get('productos/categoria/{slug}', 'Cliente\ProductoController@categoria')->name('productos.categoria');
*/


/* contacto */
Route::view('contacto', 'cliente.contacto')->name('contacto');
Route::post('mail/contacto', 'ContactoController@mailContacto')->name('mail.contacto');
Route::get('email', function() {
    return new \App\Mail\Contacto();
});

/*
 *  Rutas Protegidas
 * */
Route::middleware('auth')->group(function () {
    // Rutas con prefijo admin
    Route::group(['prefix'=>'admin', 'namespace' => '\Admin', 'as'=>'admin.'],function(){
        // User controller
        Route::get('', 'UserController@index');
        Route::post('users/desactivar/{id}', 'UserController@disable')->name('users.desactivar');
        Route::post('users/activar/{id}', 'UserController@enable')->name('users.activar');
        Route::resource('users','UserController');



        // Comunicado controller
        Route::get('comunicados/{categoria}/create', 'ComunicadoController@create')->name('comunicados.create');
        Route::get('comunicados/{categoria}', 'ComunicadoController@indexPorCategoria');

        Route::get('comunicados/{categoria}/create', 'ComunicadoController@create')->name('comunicados.create');
        Route::post('comunicados/activar/{id}', 'ComunicadoController@enable')->name('comunicados.activar');
        Route::post('comunicados/desactivar/{id}', 'ComunicadoController@disable')->name('comunicados.desactivar');

        Route::resource('comunicados','ComunicadoController', ['only' => ['edit', 'store', 'update', 'destroy']]);




        Route::resource('certificado/calidad','QualityCertificateController');
        Route::post('certificado/calidad/activar/{id}', 'QualityCertificateController@Enable')->name('qualities.enable');
        Route::post('certificado/calidad/desactivar/{id}', 'QualityCertificateController@Disable')->name('qualities.disable');

// parrafos controller


        //Route::get('parrafos/', 'ParrafoController@index')->name('parrafos.index');
        //Route::get('parrafos/{id}/edit', 'ParrafoController@edit')->name('parrafos.edit');
        //  Route::get('parrafos/{id}/update', 'ParrafoController@update')->name('parrafos.update');
        //  Route::get('parrafos/create', 'ParrafoController@create')->name('parrafos.create');
        Route::get('parrafos/destroy/{id}', 'ParrafoController@destroy')->name('parrafos.destroy');

        Route::resource('parrafos','ParrafoController', ['only' => ['edit', 'store', 'update', 'destroy', 'index', 'create']]);


        // Servicio controller
        Route::post('servicios/activar/{id}', 'ServicioController@enable')->name('servicios.activar');
        Route::post('servicios/desactivar/{id}', 'ServicioController@disable')->name('servicios.desactivar');
        Route::resource('servicios','ServicioController', ['only' => ['index', 'create', 'store', 'edit', 'destroy', 'update']]);

        // Secciones controller
        //
        Route::resource('secciones','SeccionController', ['only' => ['store']]);
        Route::get('secciones/{servicio}/create','SeccionController@createByModel')->name('secciones.model.create');

        // Fotografia controller
        Route::post('galerias/activar/{id}', 'FotografiaController@enable')->name('galerias.activar');
        Route::post('galerias/desactivar/{id}', 'FotografiaController@disable')->name('galerias.desactivar');
        Route::resource('galerias','FotografiaController', ['only' => ['index', 'create', 'store', 'edit', 'destroy']]);

        // Galería controller
        Route::post('galeria/image/remove/{id}','GaleriaController@removeImageFromGallery');
        Route::post('galeria/image/add/{id}','GaleriaController@addImageGallery')->name('gallery.image.add');
        Route::resource('galeria','GaleriaController', ['only' => ['update']]);

        // Promocion controller
        /*
         * En estas se repite admin en la url de la siguiente forma: /admin/admin/promociones/activar/{id}
         * verificar si no afecta el comportamiento y eliminar
         *
         * */
        Route::post('admin/promociones/activar/{id}', 'PromocionController@Enable')->name('promociones.activar');
        Route::post('admin/promociones/desactivar/{id}', 'PromocionController@Disable')->name('promociones.desactivar');


        Route::resource('promociones','PromocionController', ['except' =>
            ['show']
        ]);


        // Producto controller

        Route::post('/productos/activar/{id}', 'ProductoController@Enable')->name('productos.activar');
        Route::post('/productos/desactivar/{id}', 'ProductoController@Disable')->name('productos.desactivar');
        // Route::resource('productos','ProductoController', ['only' => ['index', 'create', 'store', 'edit', 'destroy', 'update']]);
        Route::post('/productos/{producto}', 'ProductoController@update')->name('productos.update');
        Route::resource('productos','ProductoController', ['only' => ['index', 'create', 'store', 'edit', 'destroy']]);

        Route::group(['prefix'=>'productos', 'as'=>'productos.'],function(){

            // CategoriaProductoController
            Route::get('categorias/obtener', 'CategoriaProductoController@categories')->name('categorias.obtener');
            Route::resource('categorias','CategoriaProductoController', ['only' => ['index', 'store', 'destroy', 'update']]);
        });
        /*// Producto controller
        Route::resource('productos','ProductoController', ['only' => ['index', 'create']]);*/

    }) ;
});



// Rutas únicas del proyecto
// Servicios
Route::group(['prefix'=>'servicios', 'as'=>'servicios.'],function(){
    Route::get('proyectos-y-construccion', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Proyectos y construcción');
        })->get();
        return view('cliente.servicios.proyectos-y-construccion', compact('servicios'));
    });
    Route::get('mantenimiento-residencial', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Mantenimiento residencial');
        })->get();
        return view('cliente.servicios.mantenimiento-residencial', compact('servicios'));
    });
    Route::get('diseno-mobiliario-y-decoracion', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Diseño mobiliario y decoración');
        })->get();
        return view('cliente.servicios.diseno-mobiliario-y-decoracion', compact('servicios'));
    });
});
// Materiales


Route::get('materiales/{material}', 'Cliente\ProductoController@index');


/*
Route::get('materiales/{material}', function ($material = null) {

   $producto = App\Producto::where('slug', 'like', '%' . $material . '%')->first();

   //sacar la galeria del producto



   $productos = App\Producto::whereHas('categorias', function ($query) {
       $query->where('nombre', '$material');
   })->get();


    return view('cliente.materiales.material', compact('producto'));
});
*/


/*
Route::group(['prefix'=>'materiales', 'as'=>'materiales.'],function(){





    Route::get('lajas', function () {


        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'lajas');
        })->get();


        return view('cliente.materiales.lajas', compact('productos'));
    });





    Route::get('basalto', function () {
        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'basalto');
        })->get();
        return view('cliente.materiales.basalto', compact('productos'));
    });
    Route::get('cantera', function () {
        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'cantera');
        })->get();
        return view('cliente.materiales.cantera', compact('productos'));
    });
    Route::get('marmol', function () {
        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'marmol');
        })->get();
        return view('cliente.materiales.marmol', compact('productos'));
    });

    Route::get('granito', function () {
        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'granito');
        })->get();
        return view('cliente.materiales.granito', compact('productos'));
    });

app/Parrafo.php
<?php


namespace App;


use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use App\Traits\DateFormater;
use Spatie\Translatable\HasTranslations;


class parrafo extends Model
{
    use HasTranslations;

    //para que la suba
    //
    public $translatable = ['titulo', 'contenido'];

    protected $table = "parrafos";
    protected $fillable = ['ref','titulo', 'contenido', 'categoria_id'];


    public function categoria()
    {
        return $this->belongsTo('App\CategoriaParrafo');
    }
}

app/Http/Controllers/Admin/ParrafoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Comunicado;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\CategoriaParrafo;


use App\Parrafo;

use Carbon\Carbon;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\DB;


class ParrafoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $parrafos = Parrafo::with('categoria')->orderBy('categoria_id','desc')->get();

        $categorias = CategoriaParrafo::select('id','nombre')->orderBy('nombre', 'asc')->get();



        return view('admin.modulos.parrafos.index', compact('parrafos','categorias'));
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $parrafo = new Parrafo();

        $parrafo->accionTit = 'Crear';
        $parrafo->method = "CREATE";
        $parrafo->link = "admin.parrafos.store";
        $parrafo->categoria = 'null';
        $parrafo->id = 0;

        $categorias = CategoriaParrafo::select('id','nombre')->orderBy('nombre', 'asc')->get();


        return view('admin.modulos.parrafos.forma', compact('parrafo','categorias'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $parrafo = new Parrafo($request->except('_token'));
        $parrafo->save();

        $mensaje = "El parrafo se agregó exitósamente";
        $tipo = "success";

        return redirect('/admin/parrafos')->with(['mensaje' => $mensaje, 'tipo' => $tipo]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $parrafo = Parrafo::find($id);


        $parrafo->accionTit = "Editar";
        $parrafo->method = "PATCH";
        $parrafo->link = "/admin/parrafos/$parrafo->id";

        $categorias = CategoriaParrafo::select('id','nombre')->orderBy('nombre', 'asc')->get();



        return view('admin.modulos.parrafos.forma', compact('parrafo', 'categorias'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $parrafo = Parrafo::find($id);
        $parrafo->fill($request->all());

        //dd($parrafo);

        $parrafo->save();

        $mensaje = "El comunicado se actualizó exitósamente";
        $tipo = "success";

        return redirect("/admin/parrafos/")->with(['mensaje' => $mensaje, 'tipo' => $tipo]);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        Parrafo::destroy($id);

        $mensaje = "El parrafo se eliminó exitósamente";
        $tipo = "success";

        return redirect("/admin/parrafos/")->with(['mensaje' => $mensaje, 'tipo' => $tipo]);
    }
}

resources/views/admin/modulos/parrafos/create.blade.php
@extends('admin.layout.admin')
@section('contenido')

    <form action="{{ route('admin.parrafos.store') }}" csrf_token="{{ csrf_token() }}">

        aquí va la forma

    </form>


@endsection

resources/views/admin/modulos/parrafos/forma.blade.php
@extends('admin.layout.admin')
@section('contenido')

    <template>
        <card>
            <p slot="title">Parrafo {{ $parrafo->accionTit }}</p>



            <div slot="content">



                @if($parrafo->method == 'PATCH')
                    <form  action="{{ $parrafo->link }}" method="post" enctype="multipart/form-data">
                        @else
                            <form  action="{{ route($parrafo->link) }}" method="post" enctype="multipart/form-data">
                                @endif

                                {{ csrf_field() }}
                                @if( $parrafo->method  == 'PATCH' )
                                    <input type="hidden" name="_method" value = "PATCH">
                                @endif
                                <input type="hidden" name="id" value="{{ $parrafo->id }}">


                                <!-- Categoria -->
                                <div class="select is-smal">

                                    <select  name="categoria_id">
                                        @foreach($categorias as $categoria)
                                            <option value="{{$categoria->id}}"  @if($categoria->id == $parrafo->categoria_id)  selected  @endif>{{$categoria->nombre}}</option>
                                        @endforeach
                                    </select>
                                    <br>
                                </div>


                               <!--referencia -->
                                <div class="columns">
                                    <div class="column is-6">
                                        <input-form>
                                            <label slot="label" class="label">Referencia única</label>
                                            <input  name="ref"  type="text" class="input" value="{{ $parrafo->ref }}">
                                        </input-form>
                                    </div>
                                </div>

                                <!-- Nombre  -->
                                <div class="columns">
                                    <div class="column is-6">
                                        <input-form>
                                            <label slot="label" class="label">Nombre</label>
                                            <input  name="titulo"  type="text" class="input" value="{{ $parrafo->titulo }}">


                                        </input-form>
                                    </div>
                                </div>
                                <!-- Descripción -->
                                <input-form >
                                    <label slot="label" class="label">Descripción</label>
                                    <textarea  name="contenido" class="textarea"> {{ $parrafo->contenido }} </textarea>

                                </input-form>


                                <div slot="footer" class="box is-radiusless card-footer-item has-text-right">
                                    <button class="button is-link is-rounded" >{{ $parrafo->accionTit }}</button>
                                </div>

                            </form>
            </div>

        </card>
    </template>


@endsection

resources/views/admin/modulos/parrafos/index.blade.php
@extends('admin.layout.admin')
@section('contenido')
    <a href="{{ route('admin.parrafos.create') }}" class="button is-info is-small is-rounded btn-create-model">Crear Parrafo</a>




    <card class="-has-content-paddingless">
        <p slot="title">Parrafos </p>
        <div slot="content">
            <table class="table is-fullwidth table is-bordered is-marginless -listado">
                <thead>
                <tr>
                    <th class="title is-6" width="170">Categoría</th>
                    <th class="title is-6" width="250">Referencia</th>
                    <th class="title is-6">Titulo</th>
                    <th class="title is-6">Contenido</th>
                    <th class="title is-6">Acciones</th>

                </tr>
                </thead>


                <tbody>
                @foreach($parrafos as $parrafo)
                    <tr>
                        <td>{{ $parrafo->categoria_id  }} - {{ $parrafo->categoria->nombre }}</td>

                        <td>
                            <a href="{{ route('admin.parrafos.edit', $parrafo->id) }}">@if($parrafo->ref){{ $parrafo->ref }}@else editar @endif </a>
                        </td>

                        <td>
                            <a href="{{ route('admin.parrafos.edit', $parrafo->id) }}">@if($parrafo->titulo){{ $parrafo->titulo }}@else editar @endif </a>
                        </td>

                        <td>{!! \Illuminate\Support\Str::words($parrafo->contenido, 50) !!}</td>

                        <td class="has-text-centered -actions">

                            <a href="/admin/parrafos/destroy/{{ $parrafo->id }}" class=""><i class="fas fa-trash-alt is-size-3"></i></a>

                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </card>
@stop