routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Language
Route::get('lang/{locale}', function ($locale) {
    // App::setLocale(session($locale));
    Session(['lang' => $locale]);
    return redirect()->back();
})->name('lang');

Route::get('/', 'HomeController@index')->name('home');
Route::get('home', function() {
    return redirect('admin');
});

/*
 *  Rutas Comunicados
 * */
Route::get('comunicados/{categoria}/{slug}', 'Cliente\ComunicadoController@detalle');
Route::resource('comunicados', 'Cliente\ComunicadoController', ['only' => ['index']]);

/*
 * Rutas estáticas (se pueden editar con tinymce)
 *
 * */

Route::get('quienes-somos', 'Cliente\EstaticoController@quienesSomos')->name('quienes-somos');

Route::get('productos', 'Cliente\EstaticoController@PRODUCTOS')->name('productos');

Route::get('calidad', 'Cliente\EstaticoController@calidad')->name('calidad');
Route::get('tecnologia', 'Cliente\EstaticoController@tecnologia')->name('tecnologia');
Route::get('diseno', 'Cliente\EstaticoController@diseno')->name('diseno');
Route::get('quienes-somos', 'Cliente\EstaticoController@quienesSomos')->name('quienes-somos');
Route::get('proveedores', 'Cliente\EstaticoController@proveedores')->name('proveedores');
Route::get('sustentabilidad', 'Cliente\EstaticoController@sustentabilidad')->name('sutentabilidad');


Route::get('aviso-de-privacidad', 'Cliente\EstaticoController@avisoPrivacidad')->name('aviso-de-privacidad');
//Route::view('/aviso-de-privacidad', 'cliente.aviso-de-privacidad');





Route::get('areas-de-practica', 'Cliente\EstaticoController@areasDePractica')->name('areas-de-practica');

Route::view('/ubicacion', 'cliente.ubicacion');


/*Rutas Galerias*/
Route::get('galeria', 'Cliente\GaleriaController@index')->name('galerias.index');
Route::get('galeria/{slug}', 'Cliente\GaleriaController@detalle')->name('galerias.detalle');

/* Rutas promociones */
Route::get('promociones/{slug}', 'Cliente\PromocionController@show')->name('promociones.show');

/* Rutas productos
Route::get('productos', 'Cliente\ProductoController@index')->name('productos.index');
Route::get('productos/{slug}', 'Cliente\ProductoController@show')->name('productos.show');
Route::get('productos/categoria/{slug}', 'Cliente\ProductoController@categoria')->name('productos.categoria');
*/


/* contacto */
Route::view('contacto', 'cliente.contacto')->name('contacto');
Route::post('mail/contacto', 'ContactoController@mailContacto')->name('mail.contacto');
Route::get('email', function() {
    return new \App\Mail\Contacto();
});

/*
 *  Rutas Protegidas
 * */
Route::middleware('auth')->group(function () {
    // Rutas con prefijo admin
    Route::group(['prefix'=>'admin', 'namespace' => '\Admin', 'as'=>'admin.'],function(){
        // User controller
        Route::get('', 'UserController@index');
        Route::post('users/desactivar/{id}', 'UserController@disable')->name('users.desactivar');
        Route::post('users/activar/{id}', 'UserController@enable')->name('users.activar');
        Route::resource('users','UserController');



        // Comunicado controller
        Route::get('comunicados/{categoria}/create', 'ComunicadoController@create')->name('comunicados.create');
        Route::get('comunicados/{categoria}', 'ComunicadoController@indexPorCategoria');

        Route::get('comunicados/{categoria}/create', 'ComunicadoController@create')->name('comunicados.create');
        Route::post('comunicados/activar/{id}', 'ComunicadoController@enable')->name('comunicados.activar');
        Route::post('comunicados/desactivar/{id}', 'ComunicadoController@disable')->name('comunicados.desactivar');

        Route::resource('comunicados','ComunicadoController', ['only' => ['edit', 'store', 'update', 'destroy']]);




        Route::resource('certificado/calidad','QualityCertificateController');
        Route::post('certificado/calidad/activar/{id}', 'QualityCertificateController@Enable')->name('qualities.enable');
        Route::post('certificado/calidad/desactivar/{id}', 'QualityCertificateController@Disable')->name('qualities.disable');

// parrafos controller


        //Route::get('parrafos/', 'ParrafoController@index')->name('parrafos.index');
        //Route::get('parrafos/{id}/edit', 'ParrafoController@edit')->name('parrafos.edit');
        //  Route::get('parrafos/{id}/update', 'ParrafoController@update')->name('parrafos.update');
        //  Route::get('parrafos/create', 'ParrafoController@create')->name('parrafos.create');
        Route::get('parrafos/destroy/{id}', 'ParrafoController@destroy')->name('parrafos.destroy');

        Route::resource('parrafos','ParrafoController', ['only' => ['edit', 'store', 'update', 'destroy', 'index', 'create']]);


        // Servicio controller
        Route::post('servicios/activar/{id}', 'ServicioController@enable')->name('servicios.activar');
        Route::post('servicios/desactivar/{id}', 'ServicioController@disable')->name('servicios.desactivar');
        Route::resource('servicios','ServicioController', ['only' => ['index', 'create', 'store', 'edit', 'destroy', 'update']]);

        // Secciones controller
        //
        Route::resource('secciones','SeccionController', ['only' => ['store']]);
        Route::get('secciones/{servicio}/create','SeccionController@createByModel')->name('secciones.model.create');

        // Fotografia controller
        Route::post('galerias/activar/{id}', 'FotografiaController@enable')->name('galerias.activar');
        Route::post('galerias/desactivar/{id}', 'FotografiaController@disable')->name('galerias.desactivar');
        Route::resource('galerias','FotografiaController', ['only' => ['index', 'create', 'store', 'edit', 'destroy']]);

        // Galería controller
        Route::post('galeria/image/remove/{id}','GaleriaController@removeImageFromGallery');
        Route::post('galeria/image/add/{id}','GaleriaController@addImageGallery')->name('gallery.image.add');
        Route::resource('galeria','GaleriaController', ['only' => ['update']]);

        // Promocion controller
        /*
         * En estas se repite admin en la url de la siguiente forma: /admin/admin/promociones/activar/{id}
         * verificar si no afecta el comportamiento y eliminar
         *
         * */
        Route::post('admin/promociones/activar/{id}', 'PromocionController@Enable')->name('promociones.activar');
        Route::post('admin/promociones/desactivar/{id}', 'PromocionController@Disable')->name('promociones.desactivar');


        Route::resource('promociones','PromocionController', ['except' =>
            ['show']
        ]);


        // Producto controller

        Route::post('/productos/activar/{id}', 'ProductoController@Enable')->name('productos.activar');
        Route::post('/productos/desactivar/{id}', 'ProductoController@Disable')->name('productos.desactivar');
        // Route::resource('productos','ProductoController', ['only' => ['index', 'create', 'store', 'edit', 'destroy', 'update']]);
        Route::post('/productos/{producto}', 'ProductoController@update')->name('productos.update');
        Route::resource('productos','ProductoController', ['only' => ['index', 'create', 'store', 'edit', 'destroy']]);

        Route::group(['prefix'=>'productos', 'as'=>'productos.'],function(){

            // CategoriaProductoController
            Route::get('categorias/obtener', 'CategoriaProductoController@categories')->name('categorias.obtener');
            Route::resource('categorias','CategoriaProductoController', ['only' => ['index', 'store', 'destroy', 'update']]);
        });
        /*// Producto controller
        Route::resource('productos','ProductoController', ['only' => ['index', 'create']]);*/

    }) ;
});



// Rutas únicas del proyecto
// Servicios
Route::group(['prefix'=>'servicios', 'as'=>'servicios.'],function(){
    Route::get('proyectos-y-construccion', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Proyectos y construcción');
        })->get();
        return view('cliente.servicios.proyectos-y-construccion', compact('servicios'));
    });
    Route::get('mantenimiento-residencial', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Mantenimiento residencial');
        })->get();
        return view('cliente.servicios.mantenimiento-residencial', compact('servicios'));
    });
    Route::get('diseno-mobiliario-y-decoracion', function () {
        $servicios = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'Diseño mobiliario y decoración');
        })->get();
        return view('cliente.servicios.diseno-mobiliario-y-decoracion', compact('servicios'));
    });
});
// Materiales


Route::get('materiales/{material}', 'Cliente\ProductoController@index');


/*
Route::get('materiales/{material}', function ($material = null) {

   $producto = App\Producto::where('slug', 'like', '%' . $material . '%')->first();

   //sacar la galeria del producto



   $productos = App\Producto::whereHas('categorias', function ($query) {
       $query->where('nombre', '$material');
   })->get();


    return view('cliente.materiales.material', compact('producto'));
});
*/


/*
Route::group(['prefix'=>'materiales', 'as'=>'materiales.'],function(){





    Route::get('lajas', function () {


        $productos = App\Producto::whereHas('categorias', function ($query) {
            $query->where('nombre', 'lajas');
        })->get();


        return view('cliente.materiales.lajas', compact('productos'));

app/Producto.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use Spatie\Translatable\HasTranslations;


class Producto extends Model
{
    use Sluggable, HasTranslations;

    public $translatable = ['slug', 'nombre', 'descripcion', 'detalles', 'descripcion'];

    protected $table = "productos";
    protected $fillable = ['nombre', 'precio', 'descripcion', 'detalles', 'slug', 'fotolistado'];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'nombre'
            ]
        ];
    }

    public function galerias () {
        return $this->morphMany(Galeria::class,'galeriable');
    }

    public function categorias () {
        return $this->belongsToMany(CategoriaProducto::class, 'cat_producto');
    }


    /**
     * @param $fotolistado
     */
    public function setFotolistadoAttribute($fotolistado)
    {
        if(!$fotolistado){
            return null;
        }
        $name = Carbon::now()->month
            ."-".Carbon::now()->day
            ."-".Carbon::now()->hour
            ."-".Carbon::now()->minute
            ."-".Carbon::now()->second
            ."-".$fotolistado->getClientOriginalName();
        $this->attributes['fotolistado'] = $name;
        \Storage::disk('productos')->put($name,\File::get($fotolistado));

    }
    public function getUrlFotolistadoAttribute () {
        if($this->fotolistado) {
            return config('app.url')."/files/productos/" . $this->fotolistado;
        }
        return "/base/img/imagen-no-disponible.jpg";
    }
    public function getLinkdetalleAttribute(){
        $producto = Producto::find($this->id);
        $url = '/productos/'.$this->slug;
        return $url;
    }

    public function getNombreAttribute($value)
    {
        try {
            $json = json_decode($value, true)[app()->getLocale()];
            if($json) {
                return $json;
            } else {
                return $value;
            }
        } catch(\Exception $exception) {
            return '';
        }
    }

    public function getDescripcionAttribute($value)
    {

        // Buscamos el idioma en el string
        // $hasLang = strpos($value, '"'.app()->getLocale().'":');
        // if($hasLang) {
        //     $json = json_decode($value, true)[app()->getLocale()];
        //     return $json;
        // }
        // return '';
        try {
            $json = json_decode($value, true)[app()->getLocale()];
            if($json) {
                return $json;
            } else {
                return $value;
            }
        } catch(\Exception $exception) {
            return '';
        }
    }

    public function getDetallesAttribute($value)
    {
        // $hasLang = strpos($value, '"'.app()->getLocale().'":');
        // if($hasLang) {
        //     $json = json_decode($value, true)[app()->getLocale()];
        //     return $json;
        // }
        // return '';
        try {
            $json = json_decode($value, true)[app()->getLocale()];
            if($json) {
                return $json;
            } else {
                return $value;
            }
        } catch(\Exception $exception) {
            return '';
        }
    }
}

app/Http/Controllers/Cliente/ComunicadoController.php
<?php

namespace App\Http\Controllers\Cliente;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Comunicado;
use App\CategoriaComunicado;

class ComunicadoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categoriasComunicados = Comunicado::where('active',1)->where('categoria_id', 1)->orderBy('fecha','desc')->paginate(6);

        return view('cliente.comunicados', compact('categoriasComunicados'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //DB
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    public function detalle($categoria, $slug)
    {
        $comunicado = Comunicado::where('slug', 'like', '%' . $slug . '%')->first();
        if(!$comunicado){
            abort(404);
        }



        return view('cliente.comunicados.detalle', compact('comunicado'));
    }
}

app/Http/Controllers/Cliente/GaleriaController.php
<?php

namespace App\Http\Controllers\Cliente;

use App\Fotografia;
use App\Galeria;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class GaleriaController extends Controller
{
    public function index (){
        $fotografias = Fotografia::with('galerias')->get();

        return view('cliente.galerias.index', compact('fotografias'));
    }

    public function detalle($slug) {
        $galeria = Galeria::where('slug', $slug)->first();
        if (is_null($galeria)) {
            abort(404);
        }


        return view('cliente.galerias.detalle', compact('galeria'));
    }
}

app/Http/Controllers/Cliente/PromocionController.php
<?php

namespace App\Http\Controllers\Cliente;

use App\Promocion;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PromocionController extends Controller
{
    public function show ($slug) {


        $promocion = Promocion::where('slug', 'like', '%' . $slug . '%')->first();



        if (!$promocion){
            abort(404);
        }





        return view('cliente.promociones.show', compact('promocion'));
    }
}

resources/views/cliente/materiales/basalto.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Basalto')
@section('contenido')

  {{--  Parallaz  --}}
  @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/basalto.jpg') }} @endslot
    @slot('texto')
        <div class="has-text-right">
            <p class="subtitle is-2 has-text-white">
                {{ __('messages.basalto') }}
            </p>
        </div>
    @endslot
  @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
        @slot('links')
            <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.basalto') }}</a></li>
        @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
      <div class="container">
        <p>
            {{ __('messages.basaltoDesc') }}
        </p>
      </div>
    </div>

    {{--  sws  --}}
    <section class="section">
      <div class="container">
        <div class="columns">
              {{-- Mostramos 3 comunicados de la categoria --}}
              @foreach( $productos as $producto)
                  <div class="column is-4">
                      @comunicado_basico
                      @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                      @slot('titulo') {{ $producto->nombre }} @endslot
                      @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                      @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                      @endcomunicado_basico
                  </div>
              @endforeach
          </div>
      </div>
    </section>

  
@endsection

resources/views/cliente/materiales/cantera.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Cantera')
@section('contenido')

  {{--  Parallaz  --}}
  @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/cantera.jpg') }} @endslot
    @slot('texto')
        <div class="has-text-right">
            <p class="subtitle is-2 has-text-white">
                {{ __('messages.cantera') }}
            </p>
        </div>
    @endslot
  @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
        @slot('links')
            <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.cantera') }}</a></li>
        @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
      <div class="container">
        <p>
            {{ __('messages.canteraDesc') }}
        </p>
      </div>
    </div>

    {{--  sws  --}}
    <section class="section">
      <div class="container">
        <div class="columns">
              {{-- Mostramos 3 comunicados de la categoria --}}
              @foreach( $productos as $producto)
                  <div class="column is-4">
                      @comunicado_basico
                      @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                      @slot('titulo') {{ $producto->nombre }} @endslot
                      @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                      @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                      @endcomunicado_basico
                  </div>
              @endforeach
          </div>
      </div>
    </section>

  
@endsection

resources/views/cliente/materiales/granito.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Granito')
@section('contenido')

    {{--  Parallaz  --}}
    @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/granito.jpg') }} @endslot
    @slot('texto')
    <div class="has-text-right">
        <p class="subtitle is-2 has-text-white">
            {{ __('messages.granito') }}
        </p>
    </div>
    @endslot
    @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
    @slot('links')
    <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.granito') }}</a></li>
    @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
        <div class="container">
            <p>
                {{ __('messages.granitoDesc') }}
            </p>
        </div>
    </div>

    {{--  sws  --}}
    <section class="section">
        <div class="container">
            <div class="columns">
                {{-- Mostramos 3 comunicados de la categoria --}}
                @foreach( $productos as $producto)
                    <div class="column is-4">
                        @comunicado_basico
                        @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                        @slot('titulo') {{ $producto->nombre }} @endslot
                        @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                        @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                        @endcomunicado_basico
                    </div>
                @endforeach
            </div>
        </div>
    </section>


@endsection

resources/views/cliente/materiales/lajas.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Lajas')
@section('contenido')

  {{--  Parallaz  --}}
  @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/lajas.jpg') }} @endslot
    @slot('texto')
        <div class="has-text-right">
            <p class="subtitle is-2 has-text-white">
                {{ __('messages.lajas') }}
            </p>
        </div>
    @endslot
  @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
        @slot('links')
            <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.lajas') }}</a></li>
        @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
      <div class="container">
        <p>
            {{ __('messages.lajasDesc') }}
        </p>
      </div>
    </div>

    {{--  sws  --}}
    <section class="section">
      <div class="container">

         <h4 class="title is-3">{{ __('messages.galeria') }}</h4>

        <div class="columns">
              {{-- Mostramos 3 comunicados de la categoria --}}
              @foreach( $productos as $producto)
                  <div class="column is-4">
                      @comunicado_basico
                      @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                      @slot('titulo') {{ $producto->nombre }} @endslot
                      @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                      @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                      @endcomunicado_basico
                  </div>
              @endforeach
          </div>
      </div>
    </section>

  
@endsection

resources/views/cliente/materiales/marmol.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Marmol')
@section('contenido')

  {{--  Parallaz  --}}
  @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/marmol.jpg') }} @endslot
    @slot('texto')
        <div class="has-text-right">
            <p class="subtitle is-2 has-text-white">
                {{ __('messages.marmol') }}
            </p>
        </div>
    @endslot
  @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
        @slot('links')
            <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.marmol') }}</a></li>
        @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
      <div class="container">
        <p>
            {{ __('messages.marmolDesc') }}
        </p>
      </div>
    </div>

    {{--  sws  --}}
    <section class="section">
      <div class="container">
        <div class="columns">
              {{-- Mostramos 3 comunicados de la categoria --}}
              @foreach( $productos as $producto)
                  <div class="column is-4">
                      @comunicado_basico
                      @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                      @slot('titulo') {{ $producto->nombre }} @endslot
                      @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                      @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                      @endcomunicado_basico
                  </div>
              @endforeach
          </div>
      </div>
    </section>

  
@endsection

resources/views/cliente/materiales/material.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Lajas')
@section('contenido')

    {{--  Parallax  --}}
    @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/lajas.jpg') }} @endslot
    @slot('texto')
    <div class="has-text-right">
        <p class="subtitle is-2 has-text-white">
            {{ $producto->nombre }}
        </p>
    </div>
    @endslot
    @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
    @slot('links')
    <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.lajas') }}</a></li>
    @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
        <div class="container">
            <p>
                {!!  $producto->descripcion  !!}
            </p>
        </div>
    </div>

    <section class="section">
        <div class="container">

            <h4 class="title is-3">{{ __('messages.galeria') }}</h4>

            <div class="columns">

                {{-- Mostramos 3 fotos de la galería --}}
                        {{--
                @foreach( $productos as $producto)
                    <div class="column is-4">
                        @comunicado_basico
                        @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                        @slot('titulo') {{ $producto->nombre }} @endslot
                        @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                        @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                        @endcomunicado_basico
                    </div>
                @endforeach
                       --}}
            </div>
        </div>
    </section>


@endsection

resources/views/cliente/materiales/onyx.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Onyx')
@section('contenido')

    {{--  Parallaz  --}}
    @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/onyx.jpg') }} @endslot
    @slot('texto')
    <div class="has-text-right">
        <p class="subtitle is-2 has-text-white">
            {{ __('messages.onyx') }}
        </p>
    </div>
    @endslot
    @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
    @slot('links')
    <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.onyx') }}</a></li>
    @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
        <div class="container">
            <p>
                {{ __('messages.onyxDesc') }}
            </p>
        </div>
    </div>

    {{--  sws  --}}
    <section class="section">
        <div class="container">
            <div class="columns">
                {{-- Mostramos 3 comunicados de la categoria --}}
                @foreach( $productos as $producto)
                    <div class="column is-4">
                        @comunicado_basico
                        @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                        @slot('titulo') {{ $producto->nombre }} @endslot
                        @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                        @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                        @endcomunicado_basico
                    </div>
                @endforeach
            </div>
        </div>
    </section>


@endsection

resources/views/cliente/materiales/recinto.blade.php
@extends('cliente.layout.cliente')
@section('titulo', 'Recinto')
@section('contenido')

    {{--  Parallaz  --}}
    @parallax_basico
    @slot('urlImagen') {{ asset('cliente/img/titulos/recinto.jpg') }} @endslot
    @slot('texto')
    <div class="has-text-right">
        <p class="subtitle is-2 has-text-white">
            {{ __('messages.recinto') }}
        </p>
    </div>
    @endslot
    @endparallax_basico

    {{--  Breadcrumb  --}}
    @breadcrumb_basico
    @slot('links')
    <li class="is-active"><a href="#" class="has-text-white" aria-current="page">{{ __('messages.recinto') }}</a></li>
    @endslot
    @endbreadcrumb_basico

    {{--  Descripción  --}}
    <div class="section">
        <div class="container">
            <p>
                {{ __('messages.recintoDesc') }}
            </p>
        </div>
    </div>

    {{--  sws  --}}
    <section class="section">
        <div class="container">
            <div class="columns">
                {{-- Mostramos 3 comunicados de la categoria --}}
                @foreach( $productos as $producto)
                    <div class="column is-4">
                        @comunicado_basico
                        @slot('urlFotoListado') {{ $producto->Urlfotolistado }} @endslot
                        @slot('titulo') {{ $producto->nombre }} @endslot
                        @slot('introduccion'){!!  substr(strip_tags($producto->descripcion),0,100) !!} @endslot
                        @slot('urlDetalle') {{ $producto->linkdetalle }} @endslot
                        @endcomunicado_basico
                    </div>
                @endforeach
            </div>
        </div>
    </section>


@endsection